
spring.application.name=ConfigServer
server.port=1234

spring.cloud.config.server.git.uri=https://github.com/vamshi-982/config-server-repo.git
spring.cloud.config.server.git.default-label=docker
spring.cloud.config.server.git.skip-ssl-validation=true
spring.cloud.config.server.git.clone-on-start=true
#spring.cloud.config.server.git.username=vamshi-982
#spring.cloud.config.server.git.password=Sidd982@