spring.application.name=PatientService

################### Import properties from Config Server ##########################
spring.config.import=optional:configserver:http://localhost:1234
logging.level.org.springframework.cloud=DEBUG
logging.level.org.springframework.boot.context.config=DEBUG